<a href="https://colab.research.google.com/github/kidi-un/numpy_qsp/blob/main/numpy_qsp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
n=a.reshape(4,2)#this is used to convert the 1d into 2d with help of reshape keyword
c=a.reshape(2,2,2)#(the product of c*r should be the number of elements in 1d)
print(n.ndim)
print(a.ndim)
print(c.ndim)
c.reshape(-1)#this method called that falatering which is used to convert any demntional array into 1d array

2
1
3


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
import numpy as np
#sliceing
#is is used to fetch the group of values in the orderd seaquence
l=np.array([34,26,12,21,27,55,66,98,33,67,89,39])
a=l[0:3:-1]
b=l[6:3:-1]#when we use the -1 as the step value then
c=l[ :2:-1]# the start value should be grater then the end value or (it shoul be like [:4:-1])
print(a,b,c)
n=l.reshape(2,6)
m=l.reshape(3,2,2)
print("\nthe 2d array is \n",n)
print("\nthe 3d array is \n",m)
print("\n***the slecing operator***")
print(n[::-1,0:1])
print(n[0:1,0:1])
print(m[0:1,::-1,::])
print(m[0:1,0:1,::-1])
print(m[1:2:,0:1,::])


[] [66 55 27] [39 89 67 33 98 66 55 27 21]

the 2d array is 
 [[34 26 12 21 27 55]
 [66 98 33 67 89 39]]

the 3d array is 
 [[[34 26]
  [12 21]]

 [[27 55]
  [66 98]]

 [[33 67]
  [89 39]]]

***the slecing operator***
[[66]
 [34]]
[[34]]
[[[12 21]
  [34 26]]]
[[[26 34]]]
[[[27 55]]]


In [ ]:
#array operation which is used to join two or more arrays
#the size of all the array should be same
import numpy as np
n=np.array([1,2,3,4,5])
m=np.array([6,7,8,9,1])
a=n
b=m
print(b-a)
print(b+a)
print(b//a)
print(b/a)
print(b*a)
print(b%a)
print(b**a)
np.logical_and(a,b)
np.logical_or(a,b)
np.logical_not(a)


[ 5  5  5  5 -4]
[ 7  9 11 13  6]
[6 3 2 2 0]
[6.         3.5        2.66666667 2.25       0.2       ]
[ 6 14 24 36  5]
[0 1 2 1 1]
[   6   49  512 6561    1]


array([False, False, False, False, False])

In [ ]:
import numpy as np
n=np.array([1,2,3,4,5])
print(n+2)
print(n-2)
print(n*2)
print(n/2)
print(n%2)
print(n**2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]
[ 1  4  9 16 25]
