<a href="https://colab.research.google.com/github/kidi-un/numpy_qsp/blob/main/numpy_qsp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
n=a.reshape(4,2)#this is used to convert the 1d into 2d with help of reshape keyword
c=a.reshape(2,2,2)#(the product of c*r should be the number of elements in 1d)
print(n.ndim)
print(a.ndim)
print(c.ndim)
c.reshape(-1)#this method called that falatering which is used to convert any demntional array into 1d array

2
1
3


array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
import numpy as np
#sliceing
#is is used to fetch the group of values in the orderd seaquence
l=np.array([34,26,12,21,27,55,66,98,33,67,89,39])
a=l[0:3:-1]
b=l[6:3:-1]#when we use the -1 as the step value then
c=l[ :2:-1]# the start value should be grater then the end value or (it shoul be like [:4:-1])
print(a,b,c)
n=l.reshape(2,6)
m=l.reshape(3,2,2)
print(m)
print(n)
print("***the slecing operator***")


[] [66 55 27] [39 89 67 33 98 66 55 27 21]
[[[34 26]
  [12 21]]

 [[27 55]
  [66 98]]

 [[33 67]
  [89 39]]]
[[34 26 12 21 27 55]
 [66 98 33 67 89 39]]
